// Code generated by mockery v2.53.3. DO NOT EDIT.

package adapter

import (
	context "context"
	io "io"

	adapter "github.com/goharbor/harbor/src/pkg/modelsync/adapter"
	mock "github.com/stretchr/testify/mock"
)

// Adapter is an autogenerated mock type for the Adapter type
type Adapter struct {
	mock.Mock
}

// FetchFile provides a mock function with given fields: ctx, rev, path, offset
func (_m *Adapter) FetchFile(ctx context.Context, rev *adapter.Revision, path string, offset int64) (io.ReadCloser, error) {
	ret := _m.Called(ctx, rev, path, offset)

	if len(ret) == 0 {
		panic("no return value specified for FetchFile")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *adapter.Revision, string, int64) (io.ReadCloser, error)); ok {
		return rf(ctx, rev, path, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *adapter.Revision, string, int64) io.ReadCloser); ok {
		r0 = rf(ctx, rev, path, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *adapter.Revision, string, int64) error); ok {
		r1 = rf(ctx, rev, path, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HealthCheck provides a mock function with given fields: ctx
func (_m *Adapter) HealthCheck(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for HealthCheck")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Info provides a mock function with given fields: ctx
func (_m *Adapter) Info(ctx context.Context) (*adapter.Info, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Info")
	}

	var r0 *adapter.Info
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*adapter.Info, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *adapter.Info); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adapter.Info)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResolveModel provides a mock function with given fields: ctx, ref
func (_m *Adapter) ResolveModel(ctx context.Context, ref adapter.ModelRef) (*adapter.Revision, error) {
	ret := _m.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for ResolveModel")
	}

	var r0 *adapter.Revision
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, adapter.ModelRef) (*adapter.Revision, error)); ok {
		return rf(ctx, ref)
	}
	if rf, ok := ret.Get(0).(func(context.Context, adapter.ModelRef) *adapter.Revision); ok {
		r0 = rf(ctx, ref)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adapter.Revision)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, adapter.ModelRef) error); ok {
		r1 = rf(ctx, ref)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAdapter creates a new instance of Adapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Adapter {
	mock := &Adapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
